---
# Source: oes/templates/secrets/opsmx-gitops-secret.yaml
apiVersion: v1
stringData:
  # Repo uri to fetch halyard configuration
  gitcloneparam: https://keerthibingi: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@github.com/opsmx-public/isd-spin-stg.git

  # Repo details to fetch dynamic configuration
  dynamicaccountsgituri: https://github.com/opsmx-public/isd-spin-stg.git
  gituser: keerthibingi
  gittoken: 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
  dynamicAccRepository: isd-spin-stg

kind: Secret
metadata:
  name: opsmx-gitops-auth
type: Opaque
