apiVersion: v1
stringData:
  git_secret_token: ENC(r7deqiRmnLY1xY31RBnZifpiUPDSFlv1dpbYO5Nf7A/E6espGgGHXVpsADfeshtTIYgzI4UavWg=)
  AWS_ACCESS_KEY_ID: ''
  AWS_SECRET_ACCESS_KEY: ''
  git_pr_token: ''
kind: Secret
metadata:
  name: git-token
type: Opaque
