apiVersion: v1
stringData:
  config: |
    auth:
      basic:
        password: ENC(GVFZWzqqynibSii5rgbQLyGQW0xs/hE7)
        username: admin
      enabled: true
    gate:
      endpoint: http://sapor-gate:8084
kind: Secret
metadata:
  name: local-spin-cli-config
