apiVersion: v1
stringData:
  config: |
    auth:
      basic:
        password: ENC(JbdLWHHYvnrPo4Kztg5Ewf4W+lCp5ixf)
        username: admin
      enabled: true
    gate:
      endpoint: http://sapor-gate:8084
kind: Secret
metadata:
  name: spin-cli-config
