apiVersion: v1
stringData:
  JIRA_USERNAME: jayasree@opsmx.io
  JIRA_URL: https://devopsmx.atlassian.net/
  JIRA_TOKEN: ENC(NiVW00sWBUanA48QcTJ1HnMVggPknjWDluQZkMXsN4K7JyTICF6Xyw==)
kind: Secret
metadata:
  name: jira-secret
type: Opaque
