apiVersion: v1
stringData:
  JIRA_USERNAME: jayasree@opsmx.io
  JIRA_URL: https://devopsmx.atlassian.net/
  JIRA_TOKEN: ENC(vxn72Iu1A46EJSfc6VvopDjMgia+f8ScS09vJV9Yzrr2EVOIYF54OA==)
kind: Secret
metadata:
  name: jira-secret
type: Opaque
