apiVersion: v1
stringData:
  JIRA_USERNAME: jayasree@opsmx.io
  JIRA_URL: https://devopsmx.atlassian.net
  JIRA_TOKEN: ENC(SF5hl5e6tks/poAPrR5E5+9Oqu5SaAEOu8ODlN7v0KqcpU76p+Vlxw==)
kind: Secret
metadata:
  name: jira-secret
type: Opaque
