apiVersion: v1
stringData:
  JIRA_USERNAME: jayasree@opsmx.io
  JIRA_URL: https://devopsmx.atlassian.net
  JIRA_TOKEN: ENC(K4Po/DCxdVK4H//Ojac+JGdzfcNLkqzGPdS8CDvfxHBCPCivRIqigA==)
kind: Secret
metadata:
  name: jira-secret
type: Opaque
